- name: start nginx service
      service:
        name: nginx
        state: started
    
- name: start nginx service
  service:
    name: nginx
    state: restarted
  when: configuracion is changed or nginx_updated is changed